#!/usr/bin/env python3
"""Review stock/proprietary-files.candidates.txt and emit a classified report.

Deterministic: same input always produces byte-identical outputs. Does not
require the device or a dump. This does NOT decide APK/APEX/overlay extraction
and does NOT resolve ELF dependencies; see docs/BLOBS-AUDIT.md.

Usage: python3 tools/review_candidates.py
Outputs: stock/candidates-report.json and stock/proprietary-files.draft.txt
"""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANDIDATES = ROOT / 'stock' / 'proprietary-files.candidates.txt'
REPORT = ROOT / 'stock' / 'candidates-report.json'
DRAFT = ROOT / 'stock' / 'proprietary-files.draft.txt'

# Files the Android build system generates from source (device tree, fs_config,
# sepolicy, VINTF). Extracting them as blobs would fight the build; port the
# underlying source instead. Stock copies stay in stock/ as evidence.
BUILD_GENERATED_BASENAMES = {
    'build.prop', 'fs_config_dirs', 'fs_config_files', 'passwd', 'group',
    'NOTICE.xml.gz', 'ueventd.rc', 'precompiled_sepolicy',
}
BUILD_GENERATED_PREFIXES = ('precompiled_sepolicy.',)

MEDIA_EXT = {'.png', '.jpg', '.jpeg', '.webp', '.gif', '.wav', '.ogg', '.mp3',
             '.mp4', '.bmp', '.ttf'}
CALIBRATION_EXT = {'.acdb', '.qwsp', '.pcm', '.pfm'}
CONFIG_TEXT_EXT = {'.conf', '.config', '.ini', '.cfg', '.prop', '.txt', '.sql',
                   '.policy', '.features', '.permissions'}
FIRMWARE_EXT = {'.bin', '.pmd', '.fw', '.img', '.mbn', '.mdt', '.b00', '.b01',
                '.b02', '.b03', '.b04', '.b05', '.b06', '.b07', '.elf', '.cil'}


def classify(path):
    """Return (category, verdict, reason). Verdict: extract | review | port-to-source."""
    parts = path.split('/')
    partition = parts[0]
    name = parts[-1]
    ext = Path(name).suffix.lower()

    if name in BUILD_GENERATED_BASENAMES or name.startswith(BUILD_GENERATED_PREFIXES):
        return 'build-generated', 'port-to-source', 'generated by the build from source'
    if '/selinux/' in path:
        return 'sepolicy-compiled', 'port-to-source', 'compiled sepolicy; port SEPolicy source'
    if '/vintf/' in path:
        return 'vintf', 'port-to-source', 'VINTF belongs in the device tree source'
    if name.endswith('.ko'):
        return 'kernel-module', 'extract', 'prebuilt kernel module; check KMI first'
    if ext == '.apex':
        return 'apex', 'review', 'decide per APEX: prebuilt vs source-built'
    if '/overlay/' in path:
        return 'overlay', 'review', 'vendor RRO; decide prebuilt vs source overlay'
    if ext == '.apk':
        return 'apk', 'review', 'decide per app: prebuilt vs source-built'
    if '/firmware' in path or ext in FIRMWARE_EXT:
        return 'firmware', 'extract', 'hardware firmware blob'
    if ext == '.so' or '.so.' in name:
        return 'elf-lib', 'extract', 'shared library; ELF deps pending dump'
    if partition in ('vendor', 'odm') and len(parts) > 2 and parts[1] == 'bin':
        return 'elf-bin', 'extract', 'binary; ELF deps pending dump'
    if ext in CALIBRATION_EXT:
        return 'calibration', 'extract', 'hardware calibration data used by vendor daemons'
    if ext in MEDIA_EXT:
        return 'media', 'review', 'media asset; check license and necessity'
    if ext == '.xml':
        return 'config-xml', 'extract', 'configuration; verify not build-generated'
    if ext == '.rc':
        return 'init-rc', 'extract', 'init script; may need source porting instead'
    if ext == '.json':
        return 'config-json', 'extract', 'configuration data'
    if ext in CONFIG_TEXT_EXT:
        return 'config-text', 'extract', 'configuration data'
    return 'other', 'review', 'unclassified; manual review required'


def main():
    lines = CANDIDATES.read_text(encoding='utf-8').splitlines()
    entries = [ln.strip() for ln in lines if ln.strip() and not ln.startswith('#')]

    problems = []
    seen = set()
    for ln in entries:
        if ln != ln.strip() or ' ' in ln or '\t' in ln:
            problems.append({'entry': ln, 'problem': 'whitespace anomaly'})
        if ln.startswith('/'):
            problems.append({'entry': ln, 'problem': 'absolute path'})
        if ln in seen:
            problems.append({'entry': ln, 'problem': 'duplicate'})
        seen.add(ln)

    rows = []
    for ln in entries:
        category, verdict, reason = classify(ln)
        rows.append({'path': ln, 'partition': ln.split('/')[0],
                     'category': category, 'verdict': verdict, 'reason': reason})

    by_partition = Counter(r['partition'] for r in rows)
    by_category = Counter(r['category'] for r in rows)
    by_verdict = Counter(r['verdict'] for r in rows)

    anomalies = []
    for r in rows:
        p = r['path']
        if p.startswith('vendor/odm_dlkm/'):
            anomalies.append({'entry': p, 'anomaly': 'odm_dlkm path under vendor; device has no odm_dlkm partition'})
        if p.count('/') == 1:
            anomalies.append({'entry': p, 'anomaly': 'partition-root file; verify it is not a symlink artifact'})

    gaps = []
    for part in ('system_ext', 'product'):
        if by_partition.get(part, 0) == 0:
            gaps.append(f'no {part} entries yet; inventory for {part} is still missing')

    report = {
        'input': str(CANDIDATES.relative_to(ROOT)),
        'total_entries': len(entries),
        'by_partition': dict(sorted(by_partition.items())),
        'by_category': dict(sorted(by_category.items())),
        'by_verdict': dict(sorted(by_verdict.items())),
        'problems': problems,
        'anomalies': anomalies,
        'gaps': gaps,
        'dropped': [r for r in rows if r['verdict'] == 'port-to-source'],
        'review': [r for r in rows if r['verdict'] == 'review'],
    }
    REPORT.write_bytes((json.dumps(report, indent=2, ensure_ascii=False) + '\n')
                       .encode('utf-8'))

    out = [
        '# DRAFT proprietary-files.txt generated by tools/review_candidates.py',
        '# Still provisional: ELF dependencies unresolved (needs a vendor/odm dump),',
        '# APK/APEX/overlay/media entries marked review, system_ext/product missing.',
        '# Do not rename to proprietary-files.txt until docs/BLOBS-AUDIT.md is closed.',
    ]
    last_part = None
    for r in rows:
        if r['verdict'] == 'port-to-source':
            continue
        if r['partition'] != last_part:
            last_part = r['partition']
            out.append('')
            out.append(f'# --- {last_part} ---')
        suffix = '  # review' if r['verdict'] == 'review' else ''
        out.append(r['path'] + suffix)
    DRAFT.write_bytes(('\n'.join(out) + '\n').encode('utf-8'))

    print(f'entries={len(entries)} problems={len(problems)} anomalies={len(anomalies)}')
    print('by_verdict=' + json.dumps(dict(sorted(by_verdict.items()))))
    print('by_category=' + json.dumps(dict(sorted(by_category.items()))))
    for g in gaps:
        print('gap: ' + g)
    if problems:
        print('PROBLEMS FOUND; see report', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
